qawolf:
  image: qawolf/playwright-ci:v1.0.0

  script:
    - npm install
    # # Start local server
    # - npm run start & npx wait-on http://localhost:3000
    - npx qawolf test --headless

  variables:
    # configure tests with environment variables
    QAW_ARTIFACT_PATH: $CI_PROJECT_DIR/artifacts
  
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/artifacts
    expire_in: 1 week
